package com.DataFlair.mycalculator;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.TextView;
import android.widget.Toast;

import com.gkemon.XMLtoPDF.PdfGenerator;
import com.gkemon.XMLtoPDF.PdfGeneratorListener;
import com.gkemon.XMLtoPDF.model.FailureResponse;
import com.gkemon.XMLtoPDF.model.SuccessResponse;

import java.io.File;

public class MainActivity2 extends AppCompatActivity {

    private static final String TAG = "RESPONSE";
    EditText number;
    ImageView whatsapp;
    String snumber;
    String file;
    TextView itemm;
    TextView totalm;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main2);

        number=findViewById(R.id.no);
        whatsapp=findViewById(R.id.whatsapp);

        itemm = findViewById(R.id.items2);

        totalm = findViewById(R.id.grand_total2);
        Intent intent=getIntent();
        String st1=intent.getStringExtra("total");
        String st2=intent.getStringExtra("item");

        totalm.setText(intent.getStringExtra("total"));
       itemm.setText(intent.getStringExtra("item"));
        pdf();


        whatsapp.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                snumber=number.getText().toString();
                if(!snumber.equals("")) {
                    try {
                        String text = "you need to pay"+st1;// Replace with your message.

                        String toNumber = snumber; // Replace with mobile phone number without +Sign or leading zeros, but with country code
                        //Suppose your country is India and your phone number is “xxxxxxxxxx”, then you need to send “91xxxxxxxxxx”.


                        Intent intent = new Intent(Intent.ACTION_VIEW);
                        intent.setData(Uri.parse("http://api.whatsapp.com/send?phone=" + toNumber + "&text=" + text));
                        startActivity(intent);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
                else
                    Toast.makeText(MainActivity2.this,"enter number",Toast.LENGTH_SHORT).show();
            }


        });



    }

    private void pdf() {
        {
            PdfGenerator.getBuilder()
                    .setContext(getBaseContext())
                    .fromLayoutXMLSource()
                    .fromLayoutXML(R.layout.reciept_pdf)
                    /* "fromLayoutXML()" takes array of layout resources.
                     * You can also invoke "fromLayoutXMLList()" method here which takes list of layout resources instead of array. */
                    .setPageSize(PdfGenerator.PageSize.A4)
                    /* It takes default page size like A4,A5,WRAP_CONTENT.*/
                    .setFileName("Test-PDF")
                    /* It is file name */
                    .setFolderName("/FolderA")
                    /* It is folder name. If you set the folder name like this pattern (FolderA/FolderB/FolderC), then
                     * FolderA creates first.Then FolderB inside FolderB and also FolderC inside the FolderB and finally
                     * the pdf file named "Test-PDF.pdf" will be store inside the FolderB. */
                    .openPDFafterGeneration(false)
                    /* It true then the generated pdf will be shown after generated. */
                    .build(new PdfGeneratorListener() {
                        @Override
                        public void onFailure(FailureResponse failureResponse) {
                            super.onFailure(failureResponse);
                            /* If pdf is not generated by an error then you will findout the reason behind it
                             * from this FailureResponse. */
                        }
                        @Override
                        public void onStartPDFGeneration() {
                            /*When PDF generation begins to start*/
                        }

                        @Override
                        public void onFinishPDFGeneration() {
                            /*When PDF generation is finished*/
                        }

                        @Override
                        public void showLog(String log) {
                            super.showLog(log);
                            /*It shows logs of events inside the pdf generation process*/
                        }

                        @Override
                        public void onSuccess(SuccessResponse response) {
                            super.onSuccess(response);
                            Toast.makeText(MainActivity2.this,"pdf generated",Toast.LENGTH_SHORT).show();
                            /* If PDF is generated successfully then you will find SuccessResponse
                             * which holds the PdfDocument,File and path (where generated pdf is stored)*/
                            Log.d(TAG, "onSuccess() called with: response = [" + response + "]");

                            file = response.getFile().getPath();

                        }
                    });

        }
    }
}